language: java
dist: precise

cache:
  directories:
    - "$HOME/.m2"
before_cache:
  - rm -rf $HOME/.m2/repository/org/keycloak
branches:
  only:
#    - 3.2.x-gl
    - "/v\\d+\\.\\d+.\\d+/"
env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx1536m"
  matrix:
    - TESTS=unit
    - TESTS=server-group1
    - TESTS=server-group2
    - TESTS=server-group3
    - TESTS=server-group4
    - TESTS=old
    - TESTS=crossdc

jdk:
  - oraclejdk8

install: true

script: 
  - ./travis-run-tests.sh $TESTS

sudo: false
