apiVersion: apps/v1
kind: Deployment
metadata:
  name: ""
spec:
  selector:
    matchLabels:
      app: ""
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
      - args:
        - start
        imagePullPolicy: Always
        name: keycloak
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        startupProbe:
          exec:
            command:
              - curl
              - --insecure
              - --head
              - --fail
              - --silent
              - https://127.0.0.1:8443/health
          initialDelaySeconds: 2
          periodSeconds: 1
          failureThreshold: 300
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - 'content="$(cat /proc/1/io)" && while true; do [[ "$content" != "$(cat /proc/1/io)" ]] && exit 0 || sleep 1 ; done'
          initialDelaySeconds: 2
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
              - curl
              - --insecure
              - --head
              - --fail
              - --silent
              - https://127.0.0.1:8443/health/ready
          initialDelaySeconds: 2
          periodSeconds: 2
          failureThreshold: 250
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
