name: Archive Surefire reports
description: It will upload and archive surefire reports per particular test run.
inputs:
  branches-ref:
    description: 'The name of the branches reference it should run against.'
    required: false
    default: ${{ env.RELEASE_BRANCHES }}
  testrun-name:
    description: 'The name of the particular test run.'
    required: true
  reports-path:
    description: 'The path from where to get the surefire reports.'
    required: true
  keep-days:
    description: 'For how many days to store the particular artifact.'
    required: false
    default: 1

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v3
      if: ${{ !cancelled() && contains(fromJSON('${{ inputs.branches-ref }}'), github.ref) && contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) }}
      with:
        name: ${{ inputs.testrun-name }}
        path: ${{ inputs.reports-path }}
        retention-days: ${{ inputs.keep-days }}
