name: Keycloak Operator CI

on:
  push:
    branches-ignore:
      - main
      - dependabot/**
  pull_request:
  workflow_dispatch:

env:
  MAVEN_ARGS: "-B -nsu -Daether.connector.http.connectionMaxTtl=25"
  MINIKUBE_VERSION: v1.32.0
  KUBERNETES_VERSION: v1.27.10 # OCP 4.14
  MINIKUBE_MEMORY: 4096 # Without explicitly setting memory, minikube uses ~25% of available memory which might be too little on smaller GitHub runners for running the tests

defaults:
  run:
    shell: bash

concurrency:
  # Only cancel jobs for PR updates
  group: operator-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak
        with:
          upload-m2-repo: false
          upload-dist: true

  test-pod-prop:
    name: Test Pod Propagation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ]
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: vars
        run: echo "version_local=0.0.1-${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Setup Java
        uses: ./.github/actions/java-setup

      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.11.0
        with:
          minikube version: ${{ env.MINIKUBE_VERSION }}
          kubernetes version: ${{ env.KUBERNETES_VERSION }}
          github token: ${{ secrets.GITHUB_TOKEN }}
          driver: docker
          start args: --addons=ingress --memory=${{ env.MINIKUBE_MEMORY }}

      - name: Download keycloak distribution
        id: download-keycloak-dist
        uses: actions/download-artifact@v4
        with:
          name: keycloak-dist
          path: quarkus/container

      - name: Build Keycloak Docker images
        run: |
          eval $(minikube -p minikube docker-env)
          (cd quarkus/container && docker build --build-arg KEYCLOAK_DIST=$(ls keycloak-*.tar.gz) . -t keycloak:${{ env.version_local }})
          (cd operator && ./scripts/build-testing-docker-images.sh ${{ env.version_local }} keycloak custom-keycloak)

      - name: Test operator running locally
        run: |
          ./mvnw install -Poperator -pl :keycloak-operator -am \
              -Dquarkus.kubernetes.image-pull-policy=IfNotPresent \
              -Dkc.operator.keycloak.image=keycloak:${{ env.version_local }} \
              -Dtest.operator.custom.image=custom-keycloak:${{ env.version_local }} \
              -Dkc.operator.keycloak.image-pull-policy=Never \
              -Dtest=KeycloakDeploymentTest
