name: Release Keycloak Operator container

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
concurrency: keycloak-operator-container-release

env:
  JDK_VERSION: 11

jobs:
  publish:
    if: github.repository == 'keycloak/keycloak'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JDK_VERSION }}
          cache: 'maven'   

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true    
          
      - name: Container metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            keycloak/keycloak-operator
            quay.io/keycloak/keycloak-operator
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
                      
      - name: Build the operator image
        run: |
          mvn clean package -Poperator -pl :keycloak-operator -am \
              -DskipTests \
              -Dquarkus.jib.image-id-file=image-id.txt \
              -Dquarkus.container-image.build=true

      - name: Tag and push the operator images
        run: |
          echo "${{ steps.meta.outputs.tags }}" | xargs -I {} \
            sh -c "docker tag $(cat operator/app/target/image-id.txt) {} && docker push {}"
