apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - classes/META-INF/fabric8/keycloaks.keycloak.org-v1.yml
  - classes/META-INF/fabric8/keycloakrealms.keycloak.org-v1.yml
  - kubernetes/kubernetes.yml

patches:
  - kubernetes/minikube.yml
